#!/usr/bin/env python3
"""Create TableQrController.java"""
import os

base = 'D:/Individual_Projects/Coffee_Order_System'
path = base + '/cos-server/src/main/java/com/vincent/controller/admin/TableQrController.java'

content = 'package com.vincent.controller.admin;\n'
content += '\n'
content += 'import com.vincent.common.Result;\n'
content += 'import com.vincent.dto.TableQrCreateDTO;\n'
content += 'import com.vincent.service.TableQrService;\n'
content += 'import com.vincent.vo.PageVO;\n'
content += 'import com.vincent.vo.TableQrVO;\n'
content += 'import lombok.RequiredArgsConstructor;\n'
content += 'import lombok.extern.slf4j.Slf4j;\n'
content += 'import org.springframework.web.bind.annotation.*;\n'
content += '\n'
content += 'import java.util.List;\n'
content += '\n'
content += '@RestController("adminTableQrController")\n'
content += '@RequestMapping("/admin/table")\n'
content += '@RequiredArgsConstructor\n'
content += '@Slf4j\n'
content += 'public class TableQrController {\n'
content += '\n'
content += '    private final TableQrService tableQrService;\n'
content += '\n'
content += '    @GetMapping("/list")\n'
content += '    public Result<PageVO<TableQrVO>> page(\n'
content += '            @RequestParam(required = false) String keyword,\n'
content += '            @RequestParam(defaultValue = "1") Integer page,\n'
content += '            @RequestParam(defaultValue = "10") Integer pageSize) {\n'
content += '        return Result.success(tableQrService.pageQuery(keyword, page, pageSize));\n'
content += '    }\n'
content += '\n'
content += '    @GetMapping("/all")\n'
content += '    public Result<List<TableQrVO>> all() {\n'
content += '        return Result.success(tableQrService.listAll());\n'
content += '    }\n'
content += '\n'
content += '    @GetMapping("/{id}")\n'
content += '    public Result<TableQrVO> detail(@PathVariable Long id) {\n'
content += '        return Result.success(tableQrService.getDetail(id));\n'
content += '    }\n'
content += '\n'
content += '    @PostMapping\n'
content += '    public Result<Void> create(@RequestBody TableQrCreateDTO dto) {\n'
content += '        tableQrService.createTable(dto);\n'
content += '        return Result.success();\n'
content += '    }\n'
content += '\n'
content += '    @PutMapping("/{id}")\n'
content += '    public Result<Void> update(@PathVariable Long id, @RequestBody TableQrCreateDTO dto) {\n'
content += '        tableQrService.updateTable(id, dto);\n'
content += '        return Result.success();\n'
content += '    }\n'
content += '\n'
content += '    @DeleteMapping("/{id}")\n'
content += '    public Result<Void> delete(@PathVariable Long id) {\n'
content += '        tableQrService.deleteTable(id);\n'
content += '        return Result.success();\n'
content += '    }\n'
content += '}\n'

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print('Created TableQrController.java')